if(NOT SPROUT_BUILD_DIR OR NOT QT_BIN_DIR)
    message(FATAL_ERROR "Pass SPROUT_BUILD_DIR and QT_BIN_DIR")
endif()
get_filename_component(SPROUT_BUILD_DIR "${SPROUT_BUILD_DIR}" ABSOLUTE)
get_filename_component(repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(test_dir "${SPROUT_BUILD_DIR}/qml-tests")
file(MAKE_DIRECTORY "${test_dir}")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/qml/" DESTINATION "${test_dir}")
foreach(component IN ITEMS AppTextField CatalogStickyToolbar GameAchievementsPanel PlaytimeLabel)
    configure_file("${repo}/qml/components/${component}.qml" "${test_dir}/${component}.qml" COPYONLY)
endforeach()
configure_file("${repo}/qml/settings/SettingsDebridPage.qml" "${test_dir}/SettingsDebridPage.qml" COPYONLY)
configure_file("${repo}/resources/fonts/Nunito-Regular.ttf" "${test_dir}/Nunito-Regular.ttf" COPYONLY)
if(WIN32)
    set(ENV{PATH} "${SPROUT_BUILD_DIR};${QT_BIN_DIR};$ENV{PATH}")
    set(runner "${QT_BIN_DIR}/qmltestrunner.exe")
else()
    set(ENV{LD_LIBRARY_PATH} "${SPROUT_BUILD_DIR}:$ENV{LD_LIBRARY_PATH}")
    set(runner "${QT_BIN_DIR}/qmltestrunner")
endif()
set(ENV{QT_QPA_PLATFORM} "offscreen")
set(ENV{QSG_RHI_BACKEND} "software")
execute_process(COMMAND "${runner}" -input "${test_dir}"
    -import "${SPROUT_BUILD_DIR}/qml_modules" -import "${test_dir}"
    -o "${test_dir}/results.txt,txt" RESULT_VARIABLE result)
if(EXISTS "${test_dir}/results.txt")
    file(READ "${test_dir}/results.txt" output)
    message("${output}")
endif()
if(NOT result EQUAL 0)
    message(FATAL_ERROR "QML interaction tests failed: ${result}")
endif()
